### ISSUE TITLE
Can not use the module.

### ISSUE THREAD

**Issue by mrdgo** [nvmd/itpp#1]
#  Executing `autogen.sh`
[autogen_output.txt](https://github.com/nvmd/itpp/files/3537213/autogen_output.txt)

# Executing `configure`
[conf_err.txt](https://github.com/nvmd/itpp/files/3537214/conf_err.txt)
[config.log](https://github.com/nvmd/itpp/files/3537215/config.log)
[conf_out.txt](https://github.com/nvmd/itpp/files/3537216/conf_out.txt)

# Executing `make`
[make.txt](https://github.com/nvmd/itpp/files/3537219/make.txt)
[make_err.txt](https://github.com/nvmd/itpp/files/3537220/make_err.txt)

# Call for help
There seem to be some problems, that I do not understand.
Can anyone provide support?

**Comment by mawdesley** [comment]
I'm also getting `config.status: error: cannot find input file: `itpp/Makefile.in'` when trying to install on ubuntu 16.04

**Comment by nvmd** [comment]
Synced with the latest upstream. Should work
